# Generated by Django 5.0.6 on 2024-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_is_featured_product_show_in_frontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
